spring:
  data:
    mongodb:
      database: userServiceDb
      port: 27017
      host: localhost
  application:
    name: user-service
server:
  port: 9200
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true