FROM openjdk:11-jre
WORKDIR usr/lib
COPY ./target/Netflix-eureka-server-0.0.1-SNAPSHOT.jar /usr/lib/Netflix-eureka-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "Netflix-eureka-server-0.0.1-SNAPSHOT.jar"]
