spring:
  data:
    mongodb:
      database: BankDb
      port: 27017
      host: localhost
  application:
    name: bank-service
server:
  port: 9000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true